config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :trials do
    match '/scrape', to: 'trials#scrape', via: :post, on: :collection
  end
  resources :notifications

  root to: 'trials#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notification.rb
# frozen_string_literal: true

class Notification < ApplicationRecord
  belongs_to :trial
end

app/models/trial.rb
# frozen_string_literal: true

class Trial < ApplicationRecord
  has_many :notifications, dependent: :destroy

  before_save :sanitize

  def sanitize
    self.actor = actor.remove(/\AActor: /)
    self.defendant = defendant.remove(/\ADemandado: /)
    self.expedient = expedient.match(/[\d].+\/[\d].+/).to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notifications_controller.rb
# frozen_string_literal: true

class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notification_params
      params.require(:notification).permit(:date, :content)
    end
end

app/controllers/trials_controller.rb
# frozen_string_literal: true

class TrialsController < ApplicationController
  before_action :set_trial, only: %i[show edit update destroy]

  # GET /trials
  # GET /trials.json
  def index
    @trials = Trial.all
  end

  # GET /trials/1
  # GET /trials/1.json
  def show; end

  # GET /trials/new
  def new
    @trial = Trial.new
  end

  # GET /trials/1/edit
  def edit; end

  # POST /trials
  # POST /trials.json
  def create
    @trial = Trial.new(trial_params)

    respond_to do |format|
      if @trial.save
        format.html { redirect_to @trial, notice: 'Trial was successfully created.' }
        format.json { render :show, status: :created, location: @trial }
      else
        format.html { render :new }
        format.json { render json: @trial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trials/1
  # PATCH/PUT /trials/1.json
  def update
    respond_to do |format|
      if @trial.update(trial_params)
        format.html { redirect_to @trial, notice: 'Trial was successfully updated.' }
        format.json { render :show, status: :ok, location: @trial }
      else
        format.html { render :edit }
        format.json { render json: @trial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trials/1
  # DELETE /trials/1.json
  def destroy
    @trial.destroy
    respond_to do |format|
      format.html { redirect_to trials_url, notice: 'Trial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def scrape
    response = TrialsSpider.process(params[:url])
    if response && response[:status] == :completed && response[:error].nil?
      flash.now[:notice] = 'New Trial Added!!'
    else
      flash.now[:alert] = response[:error]
    end

    redirect_to trials_path
  rescue StandardError => e
    flash.now[:alert] = "Error: #{e}"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_trial
    @trial = Trial.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def trial_params
    params.require(:trial).permit(:title, :actor, :defendant, :expedient,
                                  :notification_id, :summary, :court)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/trials_helper.rb
module TrialsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebScraper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notifications/_form.html.erb
<%= form_with(model: notification, local: true) do |form| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
        <% notification.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notifications</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.date %></td>
        <td><%= notification.content %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @notification.date %>
</p>

<p>
  <strong>Content:</strong>
  <%= @notification.content %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>

app/views/trials/_form.html.erb
<%= form_with(model: trial, local: true) do |form| %>
  <% if trial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trial.errors.count, "error") %> prohibited this trial from being saved:</h2>

      <ul>
        <% trial.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :actor %>
    <%= form.text_field :actor %>
  </div>

  <div class="field">
    <%= form.label :defendant %>
    <%= form.text_field :defendant %>
  </div>

  <div class="field">
    <%= form.label :expedient %>
    <%= form.text_field :expedient %>
  </div>

  <div class="field">
    <%= form.label :notification_id %>
    <%= form.text_field :notification_id %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_field :summary %>
  </div>

  <div class="field">
    <%= form.label :court %>
    <%= form.text_field :court %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trials/edit.html.erb
<h1>Editing Trial</h1>

<%= render 'form', trial: @trial %>

<%= link_to 'Show', @trial %> |
<%= link_to 'Back', trials_path %>

app/views/trials/index.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<h1>Trials</h1>

<%= form_with(url: scrape_trials_path) do %>
  <p>Add new Trial</p>
  <%= label_tag(:url, 'URL') %>
  <%= text_field_tag(:url) %>
  <%= submit_tag('Scrape trial', disabled_with: 'Strapping...') %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Actor</th>
      <th>Defendant</th>
      <th>Expedient</th>
      <th>Notifications</th>
      <th>Summary</th>
      <th>Court</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trials.each do |trial| %>
      <tr>
        <td><%= trial.title %></td>
        <td><%= trial.actor %></td>
        <td><%= trial.defendant %></td>
        <td><%= trial.expedient %></td>
        <td>
          <% trial.notifications.each do |notification|%>
            <p><strong><%= notification.date %></strong></p>
            <p><%= notification.content %></p>
          <% end %>
        </td>
        <td><%= trial.summary %></td>
        <td><%= trial.court %></td>
        <td><%= link_to 'Show', trial %></td>
        <td><%= link_to 'Edit', edit_trial_path(trial) %></td>
        <td><%= link_to 'Destroy', trial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/trials/new.html.erb
<h1>New Trial</h1>

<%= render 'form', trial: @trial %>

<%= link_to 'Back', trials_path %>

app/views/trials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @trial.title %>
</p>

<p>
  <strong>Actor:</strong>
  <%= @trial.actor %>
</p>

<p>
  <strong>Defendant:</strong>
  <%= @trial.defendant %>
</p>

<p>
  <strong>Expedient:</strong>
  <%= @trial.expedient %>
</p>

<p>
  <strong>Notification:</strong>
  <%= @trial.notification_id %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @trial.summary %>
</p>

<p>
  <strong>Court:</strong>
  <%= @trial.court %>
</p>

<%= link_to 'Edit', edit_trial_path(@trial) %> |
<%= link_to 'Back', trials_path %>